openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  # - url: https://axum-app-api-4jms5lvplq-uc.a.run.app/v1
  - url: http://localhost:8080/v1
paths:
  /health:
    get:
      responses:
        '200':
          description: OK
