CREATE TABLE users (
  uid VARCHAR NOT NULL PRIMARY KEY,
  screen_name VARCHAR NOT NULL,
  name VARCHAR NOT NULL,
  belongs TEXT NOT NULL,
  job TEXT NOT NULL,
  bio TEXT NOT NULL,
  icon_image_url VARCHAR NOT NULL,
  cover_image_url VARCHAR NOT NULL,
  twitter_username VARCHAR NOT NULL,
  github_username VARCHAR NOT NULL,
  website_url VARCHAR NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
